version: '3'
services:
  be:
    build:
      context: ./be
      dockerfile: Dockerfile
    volumes:
      - ./be:/app
    ports:
      - "8080"
  fe:
    build:
      context: ./fe
      dockerfile: Dockerfile
    volumes:
      - ./fe:/app
    ports:
      - "3000"